export const userdataConstants = {
  GET_LATEST_REQUEST: "GET_LATEST_REQUEST",
  GET_LATEST_SUCCESS: "GET_LATEST_SUCCESS",
  GET_LATEST_ERROR: "GET_LATEST_ERROR",
  SET_SORT_FILTER: "SET_SORT_FILTER",
  SET_FAVORITES: "SET_FAVORITES"
};
