export const userdataConstants = {
  // UPDATE_DATA: 'UPDATE_DATA',
  GET_LATEST_REQUEST: "GET_LATEST_REQUEST",
  GET_LATEST_SUCCESS: "GET_LATEST_SUCCESS",
  GET_LATEST_ERROR: "GET_LATEST_ERROR",
  SET_SORT_FILTER: "SET_SORT_FILTER",
  SET_ACTIVE_USER: "SET_ACTIVE_USER"
};
